name: api_client
description: Backend API client for Project Shield
version: 0.0.1
publish_to: "none"

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  http: ^1.2.2

dev_dependencies:
  flutter_lints: ^5.0.0
