version: '3.9'
services:
  web:
    build:
      context: .
      args:
        ENCRYPTION_SALT: ${ENCRYPTION_SALT}
    ports:
      - "8080:80"
    environment:
      - ENCRYPTION_SALT=${ENCRYPTION_SALT}
