name: project_shield_workspace
publish_to: "none"

environment:
  sdk: ">=3.9.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.26.3

